# Generated by Django 3.2.9 on 2022-05-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labouratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(help_text='Note:Labouratory name must be unique!!', max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('building_num', models.PositiveSmallIntegerField(default=0, help_text='Labouratory Building umber')),
                ('floor_num', models.PositiveSmallIntegerField(default=1, help_text='Labouratory floor number')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Labouratory capacity')),
                ('total_pc', models.PositiveIntegerField(default=0, help_text='Number of PCs in the Labouratory')),
                ('chairs', models.PositiveIntegerField(default=0, help_text='Number of chairs in the Labouratory')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under maintenance', 'Under maintenance')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('Repaired', 'Repaired'), ('Damaged', 'Damaged')], max_length=10)),
                ('labouratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.labouratory')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_problem', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('repaired', models.BooleanField(default=False)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pc')),
            ],
        ),
    ]
